### ISSUE TITLE
如何设置定向用户发信息

### ISSUE THREAD

**Issue by smilestar** [amazingTest/Relationship-Maintenance#1]
照着做了之后，机器人只能在企业微信里面发消息。

**Comment by amazingTest** [comment]
微信是可以直接看到企业微信发送的消息的，如果想定向向用户发送的话 可以在 messenger.json 中配置 touser 参数

**Comment by smilestar** [comment]
我发现是微信外部用户，@all的时候也在企业微信里面，通不到微信里面，是不是我操作不对

**Comment by amazingTest** [comment]
得在企业微信管理页面扫一个微信插件的东西
